#Database
DB_HOST: localhost
DB_DATABASE_NAME: securedoc
DB_USERNAME: root
DB_PASSWORD: 12345678
DB_PORT: 3307

#Server
CONTAINER_PORT: 8000
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: xuannguyenminh3@gmail.com
EMAIL_PASSWORD: gycg sydf iuzx kvsc
VERIFY_EMAIL_HOST: http://localhost:8000

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}